server:
  port: 8092
  error:
    include:
      message: true

spring:
  application:
    name: rococo-userdata
  datasource:
    username: root
    password: secretdb
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    generate-ddl: true
  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

---
spring:
  config:
    activate:
      on-profile: 'local'
  kafka:
    bootstrap-servers: 'localhost:9092'
    consumer:
      group-id: 'userdata'
      auto-offset-reset: earliest
  datasource:
    url: jdbc:mysql://localhost:3306/rococo-userdata?serverTimezone=UTC&createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: validate
rococo-userdata:
  base-uri: 'http://127.0.0.1:8092'
---
spring:
  config:
    activate:
      on-profile: 'docker'
  kafka:
    bootstrap-servers: 'kafka:9092'
    consumer:
      group-id: 'userdata'
      auto-offset-reset: earliest
  datasource:
    url: jdbc:mysql://rococo-db:3306/rococo-userdata?serverTimezone=UTC&createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: validate
rococo-userdata:
  base-uri: 'http://userdata.rococo.dc:8092'
---