server:
  port: 8080
  error:
    include:
      message: true

spring:
  application:
    name: rococo-gateway

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

---
spring:
  config:
    activate:
      on-profile: 'local'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'

rococo-artist:
  base-uri: 'http://127.0.0.1:9002'
rococo-userdata:
  base-uri: 'http://127.0.0.1:8089'
rococo-geo:
  base-uri: 'http://127.0.0.1:8091'
rococo-museum:
  base-uri: 'http://127.0.0.1:9004'
rococo-painting:
  base-uri: 'http://127.0.0.1:9006'
rococo-client:
  base-uri: 'http://127.0.0.1:3000'

---
spring:
  config:
    activate:
      on-profile: 'docker'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://auth.rococo.dc:9000'

rococo-artist:
  base-uri: 'http://artist.rococo.dc:9002'
rococo-userdata:
  base-uri: 'http://userdata.rococo.dc:8089'
rococo-geo:
  base-uri: 'http://geo.rococo.dc:8091'
rococo-museum:
  base-uri: 'http://museum.rococo.dc:9004'
rococo-painting:
  base-uri: 'http://painting.rococo.dc:9006'
rococo-client:
  base-uri: 'http://client.rococo.dc'
---