version: '3.9'

services:
  rococo-db:
    container_name: rococo-db
    image: mysql:15.1
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
#    healthcheck:
#      test: [ "CMD", "pg_isready" ]
#      interval: 3s
#      timeout: 3s
#      retries: 5
    ports:
      - "3306:3306"
    volumes:
      - rococo:/var/lib/mysql/data
    restart: always
    networks:
      - rococo-network
    dns_search: .

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.3.2
    expose:
      - "2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - rococo-network

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.3.2
    expose:
      - "9092"
    depends_on:
      zookeeper:
        condition: service_started
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
    networks:
      - rococo-network

  auth.rococo.docker:
    container_name: auth.rococo.docker
    image: ev1av1ness/rococo-auth:latest
    ports:
      - "9000:9000"
    healthcheck:
      test: "wget --spider http://localhost:9000/actuator/health || exit 1"
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
    depends_on:
      rococo-db:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - rococo-network
    dns_search: .

  gateway.rococo.docker:
    container_name: gateway.rococo.docker
    image: ev1av1ness/rococo-gateway:latest
    ports:
      - "8090:8090"
    healthcheck:
      test: "wget --spider http://localhost:8090/actuator/health || exit 1"
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
    depends_on:
      auth.niffler.dc:
        condition: service_healthy
    networks:
      - rococo-network
    dns_search: .

  ui.rococo.docker:
    container_name: ui.rococo.docker
    image: "${FRONT_IMAGE}"
    ports:
      - "80:80"
    restart: always
    depends_on:
      gateway.rococo.docker:
        condition: service_healthy
    networks:
      - rococo-network
    dns_search: .

volumes:
  rococo:
    external: true

networks:
  rococo-network:
    driver: bridge