drop table if exists geo cascade;
drop table if exists country cascade;

create table if not exists country
(
    id           binary(16)   unique not null default (UUID_TO_BIN(UUID(), true)),
    name                 varchar(255)        not null,
    primary key (id)
);

insert into country (name) values ('Австралия');
insert into country (name) values ('Австрия');
insert into country (name) values ('Азербайджан');
insert into country (name) values ('Албания');
insert into country (name) values ('Алжир');
insert into country (name) values ('Ангола');
insert into country (name) values ('Андорра');
insert into country (name) values ('Антигуа и Барбуда');
insert into country (name) values ('Аргентина');
insert into country (name) values ('Армения');
insert into country (name) values ('Афганистан');
insert into country (name) values ('Багамские Острова');
insert into country (name) values ('Бангладеш');
insert into country (name) values ('Барбадос');
insert into country (name) values ('Бахрейн');
insert into country (name) values ('Белиз');
insert into country (name) values ('Белоруссия');
insert into country (name) values ('Бельгия');
insert into country (name) values ('Бенин');
insert into country (name) values ('Болгария');
insert into country (name) values ('Боливия');
insert into country (name) values ('Босния и Герцеговина');
insert into country (name) values ('Ботсвана');
insert into country (name) values ('Бразилия');
insert into country (name) values ('Бруней');
insert into country (name) values ('Буркина-Фасо');
insert into country (name) values ('Бурунди');
insert into country (name) values ('Бутан');
insert into country (name) values ('Вануату');
insert into country (name) values ('Ватикан');
insert into country (name) values ('Великобритания');
insert into country (name) values ('Венгрия');
insert into country (name) values ('Венесуэла');
insert into country (name) values ('Восточный Тимор');
insert into country (name) values ('Вьетнам');
insert into country (name) values ('Габон');
insert into country (name) values ('Гайана');
insert into country (name) values ('Гамбия');
insert into country (name) values ('Гана');
insert into country (name) values ('Гватемала');
insert into country (name) values ('Гвинея');
insert into country (name) values ('Гвинея-Бисау');
insert into country (name) values ('Германия');
insert into country (name) values ('Гондурас');
insert into country (name) values ('Гренада');
insert into country (name) values ('Греция');
insert into country (name) values ('Грузия');
insert into country (name) values ('Дания');
insert into country (name) values ('Демократическая Республика Конго');
insert into country (name) values ('Джибути');
insert into country (name) values ('Доминика');
insert into country (name) values ('Доминиканская Республика');
insert into country (name) values ('Египет');
insert into country (name) values ('Замбия');
insert into country (name) values ('Зимбабве');
insert into country (name) values ('Израиль');
insert into country (name) values ('Индия');
insert into country (name) values ('Индонезия');
insert into country (name) values ('Иордания');
insert into country (name) values ('Ирак');
insert into country (name) values ('Иран');
insert into country (name) values ('Ирландия');
insert into country (name) values ('Исландия');
insert into country (name) values ('Испания');
insert into country (name) values ('Италия');
insert into country (name) values ('Йемен');
insert into country (name) values ('Кабо-Верде');
insert into country (name) values ('Казахстан');
insert into country (name) values ('Камбоджа');
insert into country (name) values ('Камерун');
insert into country (name) values ('Канада');
insert into country (name) values ('Катар');
insert into country (name) values ('Кения');
insert into country (name) values ('Киргизия');
insert into country (name) values ('Кирибати');
insert into country (name) values ('Китай');
insert into country (name) values ('Колумбия');
insert into country (name) values ('Коморы');
insert into country (name) values ('Коста-Рика');
insert into country (name) values ('Кот-д’Ивуар');
insert into country (name) values ('Куба');
insert into country (name) values ('Кувейт');
insert into country (name) values ('Лаос');
insert into country (name) values ('Латвия');
insert into country (name) values ('Лесото');
insert into country (name) values ('Либерия');
insert into country (name) values ('Ливан');
insert into country (name) values ('Ливия');
insert into country (name) values ('Литва');
insert into country (name) values ('Лихтенштейн');
insert into country (name) values ('Люксембург');
insert into country (name) values ('Маврикий');
insert into country (name) values ('Мавритания');
insert into country (name) values ('Мадагаскар');
insert into country (name) values ('Малави');
insert into country (name) values ('Малайзия');
insert into country (name) values ('Мали');
insert into country (name) values ('Мальдивы');
insert into country (name) values ('Мальта');
insert into country (name) values ('Марокко');
insert into country (name) values ('Маршалловы Острова');
insert into country (name) values ('Мексика');
insert into country (name) values ('Мозамбик');
insert into country (name) values ('Молдавия');
insert into country (name) values ('Монако');
insert into country (name) values ('Монголия');
insert into country (name) values ('Мьянма');
insert into country (name) values ('Намибия');
insert into country (name) values ('Науру');
insert into country (name) values ('Непал');
insert into country (name) values ('Нигер');
insert into country (name) values ('Нигерия');
insert into country (name) values ('Нидерланды');
insert into country (name) values ('Никарагуа');
insert into country (name) values ('Новая Зеландия');
insert into country (name) values ('Норвегия');
insert into country (name) values ('Объединённые Арабские Эмираты');
insert into country (name) values ('Оман');
insert into country (name) values ('Пакистан');
insert into country (name) values ('Палау');
insert into country (name) values ('Палестина');
insert into country (name) values ('Панама');
insert into country (name) values ('Папуа — Новая Гвинея');
insert into country (name) values ('Парагвай');
insert into country (name) values ('Перу');
insert into country (name) values ('Польша');
insert into country (name) values ('Португалия');
insert into country (name) values ('Республика Гаити');
insert into country (name) values ('Республика Кипр');
insert into country (name) values ('Республика Конго');
insert into country (name) values ('Республика Корея');
insert into country (name) values ('Россия');
insert into country (name) values ('Руанда');
insert into country (name) values ('Румыния');
insert into country (name) values ('Сальвадор');
insert into country (name) values ('Самоа');
insert into country (name) values ('Сан-Марино');
insert into country (name) values ('Сан-Томе и Принсипи');
insert into country (name) values ('Саудовская Аравия');
insert into country (name) values ('Сейшельские Острова');
insert into country (name) values ('Сенегал');
insert into country (name) values ('Сент-Винсент и Гренадины');
insert into country (name) values ('Сент-Китс и Невис');
insert into country (name) values ('Сент-Люсия');
insert into country (name) values ('Сербия');
insert into country (name) values ('Сингапур');
insert into country (name) values ('Сирия');
insert into country (name) values ('Словакия');
insert into country (name) values ('Словения');
insert into country (name) values ('Соединённые Штаты Америки');
insert into country (name) values ('Соломоновы Острова');
insert into country (name) values ('Сомали');
insert into country (name) values ('Судан');
insert into country (name) values ('Суринам');
insert into country (name) values ('Сьерра-Леоне');
insert into country (name) values ('Таджикистан');
insert into country (name) values ('Таиланд');
insert into country (name) values ('Танзания');
insert into country (name) values ('Того');
insert into country (name) values ('Тонга');
insert into country (name) values ('Тринидад и Тобаго');
insert into country (name) values ('Тувалу');
insert into country (name) values ('Тунис');
insert into country (name) values ('Туркменистан');
insert into country (name) values ('Турция');
insert into country (name) values ('Уганда');
insert into country (name) values ('Узбекистан');
insert into country (name) values ('Украина');
insert into country (name) values ('Уругвай');
insert into country (name) values ('Федеративные Штаты Микронезии');
insert into country (name) values ('Фиджи');
insert into country (name) values ('Филиппины');
insert into country (name) values ('Финляндия');
insert into country (name) values ('Северная Македония');
insert into country (name) values ('Шри-Ланка');
insert into country (name) values ('Франция');
insert into country (name) values ('Хорватия');
insert into country (name) values ('Центральноафриканская Республика');
insert into country (name) values ('Чад');
insert into country (name) values ('Черногория');
insert into country (name) values ('Чехия');
insert into country (name) values ('Чили');
insert into country (name) values ('Швейцария');
insert into country (name) values ('Швеция');
insert into country (name) values ('Эквадор');
insert into country (name) values ('Экваториальная Гвинея');
insert into country (name) values ('Эритрея');
insert into country (name) values ('Эсватини');
insert into country (name) values ('Эстония');
insert into country (name) values ('Эфиопия');
insert into country (name) values ('Южно-Африканская Республика');
insert into country (name) values ('Южный Судан');
insert into country (name) values ('Ямайка');
insert into country (name) values ('Япония');

create table if not exists geo
(
    id               binary(16)   unique not null default (UUID_TO_BIN(UUID(), true)),
    city                 varchar(255)        not null,
    country_id           binary(16)          not null,
    primary key (id),
    constraint fk_geo_country foreign key (country_id) references country (id)
);

insert into geo (city, country_id) VALUES ('Сидней', (SELECT id FROM country where name = 'Австралия'));
insert into geo (city, country_id) VALUES ('Вена', (SELECT id FROM country where name = 'Австрия'));
insert into geo (city, country_id) VALUES ('Баку', (SELECT id FROM country where name = 'Азербайджан'));
insert into geo (city, country_id) VALUES ('Тирана', (SELECT id FROM country where name ='Албания'));
insert into geo (city, country_id) VALUES ('Алжир', (SELECT id FROM country where name ='Алжир'));
insert into geo (city, country_id) VALUES ('Луанда', (SELECT id FROM country where name = 'Ангола'));
insert into geo (city, country_id) VALUES ('Андорра-ла-Велья', (SELECT id FROM country where name ='Андорра'));
insert into geo (city, country_id) VALUES ('Сент-Джонс', (SELECT id FROM country where name ='Антигуа и Барбуда'));
insert into geo (city, country_id) VALUES ('Буэнос-Айрес', (SELECT id FROM country where name ='Аргентина'));
insert into geo (city, country_id) VALUES ('Ереван', (SELECT id FROM country where name ='Армения'));
insert into geo (city, country_id) VALUES ('Кабул', (SELECT id FROM country where name ='Афганистан'));
insert into geo (city, country_id) VALUES ('Нассау', (SELECT id FROM country where name ='Багамские Острова'));
insert into geo (city, country_id) VALUES ('Дакка', (SELECT id FROM country where name ='Бангладеш'));
insert into geo (city, country_id) VALUES ('Бриджтаун', (SELECT id FROM country where name ='Барбадос'));
insert into geo (city, country_id) VALUES ('Манама', (SELECT id FROM country where name ='Бахрейн'));
insert into geo (city, country_id) VALUES ('Бельмопан', (SELECT id FROM country where name ='Белиз'));
insert into geo (city, country_id) VALUES ('Минск', (SELECT id FROM country where name = 'Белоруссия'));
insert into geo (city, country_id) VALUES ('Брюссель', (SELECT id FROM country where name ='Бельгия'));
insert into geo (city, country_id) VALUES ('Порто-Ново', (SELECT id FROM country where name ='Бенин'));
insert into geo (city, country_id) VALUES ('София', (SELECT id FROM country where name = 'Болгария'));
insert into geo (city, country_id) VALUES ('Сукре', (SELECT id FROM country where name ='Боливия'));
insert into geo (city, country_id) VALUES ('Сараево', (SELECT id FROM country where name ='Босния и Герцеговина'));
insert into geo (city, country_id) VALUES ('Габороне', (SELECT id FROM country where name ='Ботсвана'));
insert into geo (city, country_id) VALUES ('Бразилиа', (SELECT id FROM country where name ='Бразилия'));
insert into geo (city, country_id) VALUES ('Бандар-Сери-Бегаван', (SELECT id FROM country where name ='Бруней'));
insert into geo (city, country_id) VALUES ('Уагадугу', (SELECT id FROM country where name ='Буркина-Фасо'));
insert into geo (city, country_id) VALUES ('Гитега', (SELECT id FROM country where name ='Бурунди'));
insert into geo (city, country_id) VALUES ('Тхимпху', (SELECT id FROM country where name ='Бутан'));
insert into geo (city, country_id) VALUES ('Порт-Вила', (SELECT id FROM country where name ='Вануату'));
insert into geo (city, country_id) VALUES ('Ватикан', (SELECT id FROM country where name ='Ватикан'));
insert into geo (city, country_id) VALUES ('Лондон', (SELECT id FROM country where name ='Великобритания'));
insert into geo (city, country_id) VALUES ('Будапешт', (SELECT id FROM country where name ='Венгрия'));
insert into geo (city, country_id) VALUES ('Каракас', (SELECT id FROM country where name ='Венесуэла'));
insert into geo (city, country_id) VALUES ('Дили', (SELECT id FROM country where name ='Восточный Тимор'));
insert into geo (city, country_id) VALUES ('Ханой', (SELECT id FROM country where name ='Вьетнам'));
insert into geo (city, country_id) VALUES ('Либревиль', (SELECT id FROM country where name ='Габон'));
insert into geo (city, country_id) VALUES ('Джорджтаун', (SELECT id FROM country where name ='Гайана'));
insert into geo (city, country_id) VALUES ('Банжул', (SELECT id FROM country where name ='Гамбия'));
insert into geo (city, country_id) VALUES ('Аккра', (SELECT id FROM country where name ='Гана'));
insert into geo (city, country_id) VALUES ('Гватемала', (SELECT id FROM country where name ='Гватемала'));
insert into geo (city, country_id) VALUES ('Конакри', (SELECT id FROM country where name ='Гвинея'));
insert into geo (city, country_id) VALUES ('Бисау', (SELECT id FROM country where name ='Гвинея-Бисау'));
insert into geo (city, country_id) VALUES ('Берлин', (SELECT id FROM country where name ='Германия'));
insert into geo (city, country_id) VALUES ('Тегусигальпа', (SELECT id FROM country where name ='Гондурас'));
insert into geo (city, country_id) VALUES ('Сент-Джорджес', (SELECT id FROM country where name ='Гренада'));
insert into geo (city, country_id) VALUES ('Афины', (SELECT id FROM country where name ='Греция'));
insert into geo (city, country_id) VALUES ('Тбилиси', (SELECT id FROM country where name ='Грузия'));
insert into geo (city, country_id) VALUES ('Копенгаген', (SELECT id FROM country where name ='Дания'));
insert into geo (city, country_id) VALUES ('Киншаса', (SELECT id FROM country where name ='Демократическая Республика Конго'));
insert into geo (city, country_id) VALUES ('Джибути', (SELECT id FROM country where name ='Джибути'));
insert into geo (city, country_id) VALUES ('Розо', (SELECT id FROM country where name ='Доминика'));
insert into geo (city, country_id) VALUES ('Санто-Доминго', (SELECT id FROM country where name ='Доминиканская Республика'));
insert into geo (city, country_id) VALUES ('Каир', (SELECT id FROM country where name ='Египет'));
insert into geo (city, country_id) VALUES ('Лусака', (SELECT id FROM country where name ='Замбия'));
insert into geo (city, country_id) VALUES ('Хараре', (SELECT id FROM country where name ='Зимбабве'));
insert into geo (city, country_id) VALUES ('Иерусалим', (SELECT id FROM country where name ='Израиль'));
insert into geo (city, country_id) VALUES ('Тель-Авив', (SELECT id FROM country where name ='Израиль'));
insert into geo (city, country_id) VALUES ('Дели', (SELECT id FROM country where name ='Индия'));
insert into geo (city, country_id) VALUES ('Джакарта', (SELECT id FROM country where name ='Индонезия'));
insert into geo (city, country_id) VALUES ('Амман', (SELECT id FROM country where name ='Иордания'));
insert into geo (city, country_id) VALUES ('Багдад', (SELECT id FROM country where name ='Ирак'));
insert into geo (city, country_id) VALUES ('Тегеран', (SELECT id FROM country where name ='Иран'));
insert into geo (city, country_id) VALUES ('Дублин', (SELECT id FROM country where name ='Ирландия'));
insert into geo (city, country_id) VALUES ('Рейкьявик', (SELECT id FROM country where name ='Исландия'));
insert into geo (city, country_id) VALUES ('Мадрид', (SELECT id FROM country where name ='Испания'));
insert into geo (city, country_id) VALUES ('Рим', (SELECT id FROM country where name ='Италия'));
insert into geo (city, country_id) VALUES ('Сана', (SELECT id FROM country where name ='Йемен'));
insert into geo (city, country_id) VALUES ('Прая', (SELECT id FROM country where name ='Кабо-Верде'));
insert into geo (city, country_id) VALUES ('Нур-Султан', (SELECT id FROM country where name ='Казахстан'));
insert into geo (city, country_id) VALUES ('Пномпень', (SELECT id FROM country where name ='Камбоджа'));
insert into geo (city, country_id) VALUES ('Яунде', (SELECT id FROM country where name ='Камерун'));
insert into geo (city, country_id) VALUES ('Оттава', (SELECT id FROM country where name ='Канада'));
insert into geo (city, country_id) VALUES ('Доха', (SELECT id FROM country where name ='Катар'));
insert into geo (city, country_id) VALUES ('Найроби', (SELECT id FROM country where name ='Кения'));
insert into geo (city, country_id) VALUES ('Бишкек', (SELECT id FROM country where name ='Киргизия'));
insert into geo (city, country_id) VALUES ('Баирики', (SELECT id FROM country where name ='Кирибати'));
insert into geo (city, country_id) VALUES ('Пекин', (SELECT id FROM country where name ='Китай'));
insert into geo (city, country_id) VALUES ('Богота', (SELECT id FROM country where name ='Колумбия'));
insert into geo (city, country_id) VALUES ('Морони', (SELECT id FROM country where name ='Коморы'));
insert into geo (city, country_id) VALUES ('Сан-Хосе', (SELECT id FROM country where name ='Коста-Рика'));
insert into geo (city, country_id) VALUES ('Ямусукро', (SELECT id FROM country where name ='Кот-д’Ивуар'));
insert into geo (city, country_id) VALUES ('Гавана', (SELECT id FROM country where name ='Куба'));
insert into geo (city, country_id) VALUES ('Эль-Кувейт', (SELECT id FROM country where name ='Кувейт'));
insert into geo (city, country_id) VALUES ('Вьентьян', (SELECT id FROM country where name ='Лаос'));
insert into geo (city, country_id) VALUES ('Рига', (SELECT id FROM country where name ='Латвия'));
insert into geo (city, country_id) VALUES ('Масеру', (SELECT id FROM country where name ='Лесото'));
insert into geo (city, country_id) VALUES ('Монровия', (SELECT id FROM country where name ='Либерия'));
insert into geo (city, country_id) VALUES ('Бейрут', (SELECT id FROM country where name ='Ливан'));
insert into geo (city, country_id) VALUES ('Триполи', (SELECT id FROM country where name ='Ливия'));
insert into geo (city, country_id) VALUES ('Вильнюс', (SELECT id FROM country where name ='Литва'));
insert into geo (city, country_id) VALUES ('Вадуц', (SELECT id FROM country where name ='Лихтенштейн'));
insert into geo (city, country_id) VALUES ('Люксембург', (SELECT id FROM country where name ='Люксембург'));
insert into geo (city, country_id) VALUES ('Порт-Луи', (SELECT id FROM country where name ='Маврикий'));
insert into geo (city, country_id) VALUES ('Нуакшот', (SELECT id FROM country where name ='Мавритания'));
insert into geo (city, country_id) VALUES ('Антананариву', (SELECT id FROM country where name ='Мадагаскар'));
insert into geo (city, country_id) VALUES ('Лилонгве', (SELECT id FROM country where name ='Малави'));
insert into geo (city, country_id) VALUES ('Куала-Лумпур', (SELECT id FROM country where name ='Малайзия'));
insert into geo (city, country_id) VALUES ('Бамако', (SELECT id FROM country where name ='Мали'));
insert into geo (city, country_id) VALUES ('Мале', (SELECT id FROM country where name ='Мальдивы'));
insert into geo (city, country_id) VALUES ('Валлетта', (SELECT id FROM country where name ='Мальта'));
insert into geo (city, country_id) VALUES ('Рабат', (SELECT id FROM country where name ='Марокко'));
insert into geo (city, country_id) VALUES ('Маджуро', (SELECT id FROM country where name ='Маршалловы Острова'));
insert into geo (city, country_id) VALUES ('Мехико', (SELECT id FROM country where name ='Мексика'));
insert into geo (city, country_id) VALUES ('Мапуту', (SELECT id FROM country where name ='Мозамбик'));
insert into geo (city, country_id) VALUES ('Кишинёв', (SELECT id FROM country where name ='Молдавия'));
insert into geo (city, country_id) VALUES ('Монако', (SELECT id FROM country where name ='Монако'));
insert into geo (city, country_id) VALUES ('Улан-Батор', (SELECT id FROM country where name ='Монголия'));
insert into geo (city, country_id) VALUES ('Нейпьидо', (SELECT id FROM country where name ='Мьянма'));
insert into geo (city, country_id) VALUES ('Виндхук', (SELECT id FROM country where name ='Намибия'));
insert into geo (city, country_id) VALUES ('Катманду', (SELECT id FROM country where name ='Непал'));
insert into geo (city, country_id) VALUES ('Ниамей', (SELECT id FROM country where name ='Нигер'));
insert into geo (city, country_id) VALUES ('Абуджа', (SELECT id FROM country where name ='Нигерия'));
insert into geo (city, country_id) VALUES ('Амстердам', (SELECT id FROM country where name ='Нидерланды'));
insert into geo (city, country_id) VALUES ('Манагуа', (SELECT id FROM country where name ='Никарагуа'));
insert into geo (city, country_id) VALUES ('Веллингтон', (SELECT id FROM country where name ='Новая Зеландия'));
insert into geo (city, country_id) VALUES ('Осло', (SELECT id FROM country where name ='Норвегия'));
insert into geo (city, country_id) VALUES ('Абу-Даби', (SELECT id FROM country where name ='Объединённые Арабские Эмираты'));
insert into geo (city, country_id) VALUES ('Маскат', (SELECT id FROM country where name ='Оман'));
insert into geo (city, country_id) VALUES ('Исламабад', (SELECT id FROM country where name ='Пакистан'));
insert into geo (city, country_id) VALUES ('Нгерулмуд', (SELECT id FROM country where name ='Палау'));
insert into geo (city, country_id) VALUES ('Рамалла', (SELECT id FROM country where name ='Палестина'));
insert into geo (city, country_id) VALUES ('Панама', (SELECT id FROM country where name ='Панама'));
insert into geo (city, country_id) VALUES ('Порт-Морсби', (SELECT id FROM country where name ='Папуа — Новая Гвинея'));
insert into geo (city, country_id) VALUES ('Асунсьон', (SELECT id FROM country where name ='Парагвай'));
insert into geo (city, country_id) VALUES ('Лима', (SELECT id FROM country where name ='Перу'));
insert into geo (city, country_id) VALUES ('Варшава', (SELECT id FROM country where name ='Польша'));
insert into geo (city, country_id) VALUES ('Лиссабон', (SELECT id FROM country where name ='Португалия'));
insert into geo (city, country_id) VALUES ('Порт-о-Пренс', (SELECT id FROM country where name ='Республика Гаити'));
insert into geo (city, country_id) VALUES ('Никосия', (SELECT id FROM country where name ='Республика Кипр'));
insert into geo (city, country_id) VALUES ('Браззавиль', (SELECT id FROM country where name ='Республика Конго'));
insert into geo (city, country_id) VALUES ('Сеул', (SELECT id FROM country where name ='Республика Корея'));
insert into geo (city, country_id) VALUES ('Москва', (SELECT id FROM country where name ='Россия'));
insert into geo (city, country_id) VALUES ('Санкт-Петербург', (SELECT id FROM country where name ='Россия'));
insert into geo (city, country_id) VALUES ('Кигали', (SELECT id FROM country where name ='Руанда'));
insert into geo (city, country_id) VALUES ('Бухарест', (SELECT id FROM country where name ='Румыния'));
insert into geo (city, country_id) VALUES ('Сан-Сальвадор', (SELECT id FROM country where name ='Сальвадор'));
insert into geo (city, country_id) VALUES ('Апиа', (SELECT id FROM country where name ='Самоа'));
insert into geo (city, country_id) VALUES ('Сан-Марино', (SELECT id FROM country where name ='Сан-Марино'));
insert into geo (city, country_id) VALUES ('Сан-Томе', (SELECT id FROM country where name ='Сан-Томе и Принсипи'));
insert into geo (city, country_id) VALUES ('Эр-Рияд', (SELECT id FROM country where name ='Саудовская Аравия'));
insert into geo (city, country_id) VALUES ('Сейшельские Острова', (SELECT id FROM country where name ='Сейшельские Острова'));
insert into geo (city, country_id) VALUES ('Дакар', (SELECT id FROM country where name ='Сенегал'));
insert into geo (city, country_id) VALUES ('Кингстаун', (SELECT id FROM country where name ='Сент-Винсент и Гренадины'));
insert into geo (city, country_id) VALUES ('Бастер', (SELECT id FROM country where name ='Сент-Китс и Невис'));
insert into geo (city, country_id) VALUES ('Кастри', (SELECT id FROM country where name ='Сент-Люсия'));
insert into geo (city, country_id) VALUES ('Белград', (SELECT id FROM country where name ='Сербия'));
insert into geo (city, country_id) VALUES ('Сингапур', (SELECT id FROM country where name ='Сингапур'));
insert into geo (city, country_id) VALUES ('Дамаск', (SELECT id FROM country where name ='Сирия'));
insert into geo (city, country_id) VALUES ('Братислава', (SELECT id FROM country where name ='Словакия'));
insert into geo (city, country_id) VALUES ('Любляна', (SELECT id FROM country where name ='Словения'));
insert into geo (city, country_id) VALUES ('Вашингтон', (SELECT id FROM country where name ='Соединённые Штаты Америки'));
insert into geo (city, country_id) VALUES ('Хониара', (SELECT id FROM country where name ='Соломоновы Острова'));
insert into geo (city, country_id) VALUES ('Могадишо', (SELECT id FROM country where name ='Сомали'));
insert into geo (city, country_id) VALUES ('Хартум', (SELECT id FROM country where name ='Судан'));
insert into geo (city, country_id) VALUES ('Парамарибо', (SELECT id FROM country where name ='Суринам'));
insert into geo (city, country_id) VALUES ('Фритаун', (SELECT id FROM country where name ='Сьерра-Леоне'));
insert into geo (city, country_id) VALUES ('Душанбе', (SELECT id FROM country where name ='Таджикистан'));
insert into geo (city, country_id) VALUES ('Бангкок', (SELECT id FROM country where name ='Таиланд'));
insert into geo (city, country_id) VALUES ('Додома', (SELECT id FROM country where name ='Танзания'));
insert into geo (city, country_id) VALUES ('Ломе', (SELECT id FROM country where name ='Того'));
insert into geo (city, country_id) VALUES ('Нукуалофа', (SELECT id FROM country where name ='Тонга'));
insert into geo (city, country_id) VALUES ('Порт-оф-Спейн', (SELECT id FROM country where name ='Тринидад и Тобаго'));
insert into geo (city, country_id) VALUES ('Фунафути', (SELECT id FROM country where name ='Тувалу'));
insert into geo (city, country_id) VALUES ('Тунис', (SELECT id FROM country where name ='Тунис'));
insert into geo (city, country_id) VALUES ('Ашхабад', (SELECT id FROM country where name ='Туркменистан'));
insert into geo (city, country_id) VALUES ('Стамбул', (SELECT id FROM country where name ='Турция'));
insert into geo (city, country_id) VALUES ('Кампала', (SELECT id FROM country where name ='Уганда'));
insert into geo (city, country_id) VALUES ('Ташкент', (SELECT id FROM country where name ='Узбекистан'));
insert into geo (city, country_id) VALUES ('Киев', (SELECT id FROM country where name ='Украина'));
insert into geo (city, country_id) VALUES ('Монтевидео', (SELECT id FROM country where name ='Уругвай'));
insert into geo (city, country_id) VALUES ('Паликир', (SELECT id FROM country where name ='Федеративные Штаты Микронезии'));
insert into geo (city, country_id) VALUES ('Сува', (SELECT id FROM country where name ='Фиджи'));
insert into geo (city, country_id) VALUES ('Манила', (SELECT id FROM country where name ='Филиппины'));
insert into geo (city, country_id) VALUES ('Хельсинки', (SELECT id FROM country where name ='Финляндия'));
insert into geo (city, country_id) VALUES ('Скопье', (SELECT id FROM country where name ='Северная Македония'));
insert into geo (city, country_id) VALUES ('Шри-Джаяварденепура-Котте', (SELECT id FROM country where name ='Шри-Ланка'));
insert into geo (city, country_id) VALUES ('Париж', (SELECT id FROM country where name ='Франция'));
insert into geo (city, country_id) VALUES ('Загреб', (SELECT id FROM country where name ='Хорватия'));
insert into geo (city, country_id) VALUES ('Банги', (SELECT id FROM country where name ='Центральноафриканская Республика'));
insert into geo (city, country_id) VALUES ('Нджамена', (SELECT id FROM country where name ='Чад'));
insert into geo (city, country_id) VALUES ('Подгорица', (SELECT id FROM country where name ='Черногория'));
insert into geo (city, country_id) VALUES ('Прага', (SELECT id FROM country where name ='Чехия'));
insert into geo (city, country_id) VALUES ('Сантьяго', (SELECT id FROM country where name ='Чили'));
insert into geo (city, country_id) VALUES ('Берн', (SELECT id FROM country where name ='Швейцария'));
insert into geo (city, country_id) VALUES ('Стокгольм', (SELECT id FROM country where name ='Швеция'));
insert into geo (city, country_id) VALUES ('Кито', (SELECT id FROM country where name ='Эквадор'));
insert into geo (city, country_id) VALUES ('Малабо', (SELECT id FROM country where name ='Экваториальная Гвинея'));
insert into geo (city, country_id) VALUES ('Асмэра', (SELECT id FROM country where name ='Эритрея'));
insert into geo (city, country_id) VALUES ('Лобамба', (SELECT id FROM country where name ='Эсватини'));
insert into geo (city, country_id) VALUES ('Мбабане', (SELECT id FROM country where name ='Эсватини'));
insert into geo (city, country_id) VALUES ('Таллин', (SELECT id FROM country where name ='Эстония'));
insert into geo (city, country_id) VALUES ('Аддис-Абеба', (SELECT id FROM country where name ='Эфиопия'));
insert into geo (city, country_id) VALUES ('Претория', (SELECT id FROM country where name ='Южно-Африканская Республика'));
insert into geo (city, country_id) VALUES ('Джуба', (SELECT id FROM country where name ='Южный Судан'));
insert into geo (city, country_id) VALUES ('Кингстон', (SELECT id FROM country where name = 'Ямайка'));
insert into geo (city, country_id) VALUES ('Токио', (SELECT id FROM country where name = 'Япония'));


