openapi: 3.0.0
info:
  title: Museum API
  version: 1.0.0
paths:
  /api/museum:
    get:
      summary: Get museums
      parameters:
        - name: size
          in: query
          description: The number of museums to retrieve per page
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 100
        - name: page
          in: query
          description: The page number to retrieve
          schema:
            type: integer
            format: int32
            minimum: 0
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/Museum'
#https://stackoverflow.com/questions/61307411/openapi-generator-pageable-with-spring
                  pageable:
                    $ref: '#/components/schemas/Pageable'
                  last:
                    type: boolean
                    description: Indicates if it's the last page
                  totalPages:
                    type: integer
                    format: int32
                    description: The total number of pages
                  totalElements:
                    type: integer
                    format: int64
                    description: The total number of elements
                  number:
                    type: integer
                    format: int32
                    description: The current page number
                  first:
                    type: boolean
                    description: Indicates if it's the first page
                  sort:
                    $ref: '#/components/schemas/Sort'
                  size:
                    type: integer
                    format: int32
                    description: The number of items per page
                  numberOfElements:
                    type: integer
                    format: int32
                    description: The number of elements on the current page
                  empty:
                    type: boolean
                    description: Indicates if the content is empty
components:
  schemas:
    Museum:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        photo:
          type: string
          format: byte
        geo:
          $ref: '#/components/schemas/Geo'
    Geo:
      type: object
      properties:
        city:
          type: string
          description: The city of the museum
        country:
          $ref: '#/components/schemas/Country'
    Country:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: The ID of the country
        name:
          type: string
          description: The name of the country
    Pageable:
      type: object
      properties:
        pageNumber:
          type: integer
        pageSize:
          type: integer
        sort:
          $ref: '#/components/schemas/Sort'
        offset:
          type: integer
        paged:
          type: boolean
        unpaged:
          type: boolean
    Sort:
      type: object
      properties:
        empty:
          type: boolean
        sorted:
          type: boolean
        unsorted:
          type: boolean